Repository anomaly-true/Python-CJ_9, pull requests merged in 2022-07, with the labels that each got.

#12 Simple registration system
  client/src/connection.py
  client/src/main.py
  client/src/ui/home.ui
  client/src/ui/login.ui
  client/src/views/home.py
  client/src/views/login.py
  server/src/main.py
  server/src/views/home.html
  server/src/views/register.html
Labels: feature

#11 feat: Add basic database connection and models.py - User, Code, Solution
  .gitignore
  server/src/__init__.py
  server/src/app/__init__.py
  server/src/app/database.py
  server/src/app/models.py
  server/src/app/schemas.py
  server/src/main.py
Labels: feature, changes-requested

#24 build: added jedi to the dev-requirements
  client/dev-requirements.txt
  server/dev-requirements.txt
Labels: changes-requested
